[project]
name = "odoo-addons-oca-server-ux"
version = "18.0.20250205.0"
dependencies = [
    "odoo-addon-base_technical_features==18.0.*",
    "odoo-addon-base_tier_validation==18.0.*",
    "odoo-addon-date_range==18.0.*",
    "odoo-addon-developer_menu==18.0.*",
    "odoo-addon-sequence_check_digit==18.0.*",
    "odoo-addon-server_action_mass_edit==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
